CREATE TABLE friends_tbl
	(
	  ID INT NOT NULL AUTO_INCREMENT,
		ACC_ID INT NOT NULL,
		ACC_ID_FRIEND INT NOT NULL,
		CONSTRAINT PR_KEY PRIMARY KEY (ID),
		CONSTRAINT FR_KEY_ACC_ID FOREIGN KEY(ACC_ID) REFERENCES ACCOUNT_TBL(ACC_ID) ON DELETE CASCADE,
		CONSTRAINT FR_KEY_ACC_ID_FRIEND FOREIGN KEY(ACC_ID_FRIEND) REFERENCES ACCOUNT_TBL(ACC_ID) ON DELETE CASCADE
	);