CREATE TABLE account_tbl
	(
		ACC_ID INT NOT NULL AUTO_INCREMENT,
		NAME VARCHAR(50) NOT NULL,
		MIDDLE_NAME VARCHAR(50),
		SURNAME VARCHAR(50) NOT NULL,
		DATE_OF_BIRTH DATE,
		HOME_ADDRESS VARCHAR(100),
		WORK_ADDRESS VARCHAR(100),
		EMAIL VARCHAR(50) NOT NULL,
		ICQ VARCHAR(30),
		SKYPE VARCHAR(50),
		ADD_INFO TEXT,
		PASSWORD VARCHAR(100) NOT NULL,
		IMAGE LONGBLOB,
		CONSTRAINT PR_KEY PRIMARY KEY (ACC_ID),
		CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL)
	);
