CREATE TABLE personal_phone_tbl
	(
	  PHONE_ID INT NOT NULL AUTO_INCREMENT,
		ACC_ID INT NOT NULL,
		PHONE CHAR(16),
		CONSTRAINT PR_KEY_PERSONAL_PHONES PRIMARY KEY(PHONE_ID),
		CONSTRAINT FOREIGN_KEY_PERSONAL_PHONES FOREIGN KEY(ACC_ID) REFERENCES ACCOUNT_TBL(ACC_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
	);