CREATE TABLE GROUP_TBL
	(
		GR_ID INT NOT NULL AUTO_INCREMENT,
		NAME VARCHAR(100) NOT NULL,
		IMAGE LONGBLOB,
		CONSTRAINT PR_KEY_GR_TBL_GR_ID PRIMARY KEY(GR_ID),
		CONSTRAINT UNIQUE_GR_TBL_NAME UNIQUE(NAME)
	);