CREATE TABLE ACCOUNT_TBL
	(
		ACC_ID SERIAL,
		NAME VARCHAR(50) NOT NULL,
		MIDDLE_NAME VARCHAR(50) DEFAULT 'NO_MIDDLE_NAME',
		SURNAME VARCHAR(50) NOT NULL,
		DATE_OF_BIRTH DATE,
		HOME_ADDRESS VARCHAR(100),
		WORK_ADDRESS VARCHAR(100),
		EMAIL VARCHAR(50) NOT NULL,
		ICQ VARCHAR(30),
		SKYPE VARCHAR(50),
		ADD_INFO TEXT,
		PASSWORD VARCHAR (30) NOT NULL,
		IMAGE BLOB,
		CONSTRAINT PR_KEY PRIMARY KEY (ACC_ID),
		CONSTRAINT UNIQUE_EMAIL UNIQUE(EMAIL)
	);