CREATE TABLE requests_to_friends_tbl
	(
	  ID INT NOT NULL AUTO_INCREMENT,
		ACC_ID_FROM INT NOT NULL,
		ACC_ID_TO INT NOT NULL,
		CONSTRAINT PR_KEY_REQUESTS_TO_FRIENDS_TBL  PRIMARY KEY(ID),
		CONSTRAINT FR_KEY_ACC_ID_REQUESTS_TO_FRIENDS_TBL FOREIGN KEY(ACC_ID_FROM) REFERENCES ACCOUNT_TBL(ACC_ID) ON DELETE CASCADE,
		CONSTRAINT FR_KEY_ACC_ID_FRIND_REQUESTS_TO_FRIENDS_TBL FOREIGN KEY(ACC_ID_TO) REFERENCES ACCOUNT_TBL(ACC_ID) ON DELETE CASCADE
	);