CREATE TABLE mysocialnetwork.MEMBERS_OF_GROUPS_TBL
(
    ACC_ID INT NOT NULL,
    GR_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    CONSTRAINT MEMBERS_OF_GROUPS_ACC_ID_GR_ID_pk PRIMARY KEY (ACC_ID, GR_ID),
    CONSTRAINT MEMBERS_OF_GROUPS_TBL_ACC_ID_fk FOREIGN KEY (ACC_ID) REFERENCES ACCOUNT_TBL (ACC_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT MEMBERS_OF_GROUPS_TBL_GR_ID_fk FOREIGN KEY (GR_ID) REFERENCES GROUP_TBL (GR_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT MEMBERS_OF_GROUPS_TBL_ROLE_ID_fk FOREIGN KEY (ROLE_ID) REFERENCES ROLES_FOR_GROUPS_TBL (ID) ON DELETE CASCADE ON UPDATE CASCADE;
);